import Head from "next/head";
import GivingAccordion from "src/components/GivingAccordion";
import { Button } from "@nextui-org/button";
import { ArrowLongRightIcon } from "@heroicons/react/24/solid";

export default function AboutUs() {
  return (
    <>
      {/*  items-center justify-center */}
      <Head>
        <title> Giving</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden pt-[68px]">
        <div className="min-w-screen  relative  flex h-screen w-screen items-center justify-around bg-[url('/images/giving/giving-top-bg.png')] bg-cover">
          <div className="font-bold leading-10">
            <h1 className="mb-5 text-2xl  md:text-3xl lg:text-5xl xl:text-6xl">
              {" "}
              A generous person will prosper;{" "}
            </h1>
            <h1 className="my-1 mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              Whoever refreshes
            </h1>
            <h1 className="my-1 mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              Others will be
            </h1>
            <h1 className="mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              refreshed.
            </h1>
            <br />
            <h1 className="mb-5 text-2xl md:text-3xl lg:text-4xl xl:text-5xl ">
              Proverbs 11:25{" "}
            </h1>
          </div>
          <div className="flex-none"></div>
        </div>

        <div className=" font-bold text-white">
          <div className=" h-screen w-screen bg-[url('/images/about-us/About-us-middle-bg.png')] bg-cover  sm:max-md:flex lg:flex ">
            <div className="xl:mt-44">
              <div className=" pl-24 xl:mx-24 xl:mt-0 2xl:mx-60 ">
                <div className=" pt-20 text-5xl sm:max-md:text-lg lg:text-9xl xl:pt-0">
                  Ways <br></br> We <br />
                  Give
                  <br />
                </div>
                <Button
                  color="success"
                  className="text-md mt-5 bg-[#00EDC2] px-12 py-5 font-bold text-black lg:w-72 lg:text-lg"
                >
                  Give Now
                  <ArrowLongRightIcon className="w-15 size-8" />
                </Button>
              </div>
            </div>
            <div className="w-11/12 lg:mt-44 xl:w-128">
              <GivingAccordion />
            </div>
          </div>

          {/* <div className="right-50 absolute top-20"></div> */}
          {/* <Image
            src="/About-us-middle-bg.png"
            width={100}
            height={600}
            layout="responsive"
            alt={""}
          /> */}
        </div>

        <div className="min-w-screen relative mt-10 w-screen  flex-row items-center justify-center overflow-hidden text-center">
          <h1 className="lg:text-1xl my-10 justify-center text-sm font-bold sm:text-4xl">
            {" "}
            Why Should I tithe?{" "}
          </h1>
          <h1 className="lg:text-1xl my-5 text-sm font-bold sm:text-4xl">
            When you tithe, you’re trusting God with your finances.
          </h1>
          <p className="lg:text-1xl mb-10 text-sm leading-10 sm:text-2xl">
            Tithing is a biblical principle. God calls us to give the first 10%
            of our income back to
            <br />
            Him. We’ve seen God provide abundantly in our church, and we know He
            will provide
            <br />
            abundantly for you and your family when you put Him first in your
            finances. In fact, it’s
            <br />
            the one area in the Bible where God tells you to test Him.
            <br />
            <br />
            <br />
            Malachi 3:10, God tells us to bring tithe, which is 10% of our
            income, to Him. Later,
            <br />
            Jesus affirms this in the New Testament.
          </p>
        </div>

        {/* #D9D9D9 */}
        <div className="min-w-screen relative mt-10 w-screen items-center justify-center overflow-hidden bg-[#D9D9D9] text-center">
          <br />
          <br />
          <h1 className="my-10 mt-10 text-8xl font-bold ">Need Help?</h1>
          <h1 className="my-5 text-xl">
            If you’ve got questions about what you can give and how to give it,
            we’d love to help you figure it out.{" "}
          </h1>
          <Button className="my-5 rounded-none border-b-4	border-b-black bg-[#D9D9D9] p-10 ">
            <h1 className="  inline-block text-7xl font-bold">
              {" "}
              Let&apos;s Talk{" "}
              <ArrowLongRightIcon className="size-20 inline-block w-10" />{" "}
            </h1>
          </Button>
        </div>
      </main>
    </>
  );
}
