import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function AbountUs() {
  const hallowTxtStyle = "-1px -1px 0 #f8fafc, 1px -1px 0 #f8fafc, -1px 1px 0 #f8fafc, 1px 1px 0 #f8fafc"
  const coreValueTxtStyle= "text-sm sm:text-2xl lg:text-4xl -translate-y-4 sm:-translate-y-4 "
  const coreValueNumStyle= "text-[#241F20] text-2xl sm:text-4xl lg:text-8xl -translate-y-3 sm:-translate-y-4 lg:-translate-y-7 border-t-8 border-white-500"

  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden">
        {/* VISION && MISSION */}
        <div className="relative  w-screen min-w-screen flex justify-center items-center">
          <div className="absolute top-10 left-20 sm:top-40 sm:left-40 lg:top-60 lg:left-60 font-extrabold leading-10	">
          <h1 className="text-2xl sm:text-4xl lg:text-7xl"> Our Vision  </h1>
          <h1 className="text-sm my-1 sm:text-1xl lg:text-2xl"> Antioch Church <span className="tracking-tighter	">&#x2015;</span>  </h1> 
          <h1 className="text-sm mb-5 sm:text-1xl lg:text-2xl">An apostolic and prophetic cell-based church  </h1> 

          <h1 className="text-2xl sm:text-4xl lg:text-7xl my-2">& Mission</h1>
          <h1 className="text-sm mb-5 sm:text-2xl">100 strong local churches, 100,000 disciples. </h1>

         </div>
          <Image src="/images/About-us-top-bg.png"
           width={100}
           height={800}
           layout="responsive" 
           className="min-w-0"
          />

        </div>

        {/* CORE VALUE */}
          <div className="relative w-screen font-bold text-white">
            <div className="absolute top-10 left-10 lg:top-80 lg:left-40 sm:top-40 md:left-10">
            <span className="-tracking-[.25em] text-2xl sm:text-5xl lg:text-8xl ">  </span>
              <p className={coreValueNumStyle} style={{textShadow: hallowTxtStyle}}> 02 </p>
              <h1 className={coreValueTxtStyle} > HUMILITY</h1>
            </div>

            <div className="absolute top-10 right-10 sm:top-20 sm:right-20 lg:top-40 lg:right-40">
            {/* <span className="-tracking-[.25em] text-2xl sm:text-5xl lg:text-8xl "> &#x2015; &#x2015;  &#x2015;</span> */}
              <p className={coreValueNumStyle} style={{textShadow: hallowTxtStyle}}> 01 </p>
              <h1 className={coreValueTxtStyle}> PASSIONATE</h1>
            </div>

          <div className="absolute top-0 left-0 w-full h-full flex flex-col justify-center text-1xl items-center">

            <div className="my-10">
              <h1 className="text-2xl sm:text-5xl lg:text-8xl">Core</h1>
              <h1 className="text-2xl sm:text-5xl lg:text-8xl">Values</h1>
            </div>


            <div className="m-0 ">
              {/* <span className="-tracking-[.25em] text-2xl sm:text-5xl lg:text-8xl hidden "> &#x2015;</span> */}
              <p className={coreValueNumStyle} style={{textShadow: hallowTxtStyle}}> 03 </p>
              <h1 className={coreValueTxtStyle}> INTEGRITY</h1>
            </div>
            
          </div>
          <Image src="/images/About-us-middle-bg.png"
           width={100}
           height={600}
           layout="responsive" />
        </div>

        <div className="relative w-screen font-extrabold  w-full h-full flex flex-col justify-center text-1xl items-center my-10">
          <h1 className="text-2xl sm:text-7xl"> The Experience </h1>
        </div>

        < div className="grid gird-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-2">
            <Image src="/encountering-jesus.png"
              width={800}
              height={600}
              layout=""
              className="mb-5" 
            />

            <Image src="/images/experiencing-family.png"
              width={800}
              height={600}
              layout=""
              className="mb-5" 
            /> 

            <Image src="/images/promoting-discipleship.png"
                width={800}
                height={600}
                layout=""
                className="mb-5"
              />

            <Image src="/images/growing-spiritually.png"
                width={800}
                height={600}
                layout=""
                className="mb-5" 
              />
        </div>

        <div className="relative w-screen font-extrabold  w-full h-full flex flex-col justify-center text-1xl items-center my-10">
        <hr className="border-dotted"></hr>

          <h1 className="text-2xl sm:text-7xl"> ( The FOOTER ) </h1>
        </div>

      </main>
    </>
  );

  }


