import Head from "next/head";
import Image from "next/image";
import BaptismAccordion from "~/components/BaptismAccordion";

export default function Baptism() {
  return (
    <>
      {/*  items-center justify-center */}
      <Head>
        <title> Giving</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden ">
        <div className="min-w-screen  flex h-screen w-screen items-center justify-center bg-[url('/images/baptism-top-bg.png')] bg-cover">
          <div className=" pr-40 font-bold leading-10">
            <h1 className="my-1 mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              The{" "}
            </h1>
            <h1 className="my-1 mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              old life
            </h1>
            <h1 className="my-1 mb-5 text-5xl md:text-5xl lg:text-8xl xl:text-9xl">
              {" "}
              is gone.
            </h1>
            <p>
              {" "}
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              &nbsp;
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              &nbsp;
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
              &nbsp;
              &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            </p>
            <p>
              {" "}
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
            </p>
            <p>enim ad minim veniam, quis nostrud exercitation. </p>
            <Image
              src="/images/baptise-img-1.png"
              alt="aboutUs"
              width={550}
              height={0}
              priority={true}
              layout=""
              className="absolute right-20 top-0 mr-40 min-w-0 xl:w-136"
            />

            <Image
              src="/images/baptise-img-2.png"
              alt="aboutUs"
              width={550}
              height={0}
              priority={true}
              layout=""
              className="absolute bottom-10 right-0 min-w-0 xl:w-36"
            />
          </div>
        </div>
        <br />
        <br />
        <br />
        <div className="min-w-screen  flex h-screen w-full items-center justify-center">
          <div className="w-10/12  leading-10">
            <BaptismAccordion />
          </div>
        </div>
      </main>
    </>
  );
}
