import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import GivingAccordion from "src/components/GivingAccordion";
import { Button, ButtonGroup } from "@nextui-org/button";
import { ArrowLongRightIcon } from "@heroicons/react/24/solid";

export default function AboutUs() {
  const hallowTxtStyle =
    "-1px -1px 0 #f8fafc, 1px -1px 0 #f8fafc, -1px 1px 0 #f8fafc, 1px 1px 0 #f8fafc";
  const coreValueTxtStyle =
    "text-sm sm:text-2xl lg:text-4xl -translate-y-4 sm:-translate-y-4 ";
  const coreValueNumStyle =
    "text-[#241F20] text-2xl sm:text-4xl lg:text-8xl -translate-y-3 sm:-translate-y-4 lg:-translate-y-7 border-t-8 border-white-500";

  return (
    <>
      <Head>
        <title> Giving</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="overflow-x-hidden ">
        <div className="min-w-screen relative flex w-screen items-center justify-center">
          <div className="absolute left-20 top-10 font-bold leading-10 sm:left-40 sm:top-40 lg:left-60 lg:top-60	">
            <h1 className="lg:text-1xl text-sm sm:text-4xl">
              {" "}
              A generous person will prosper;{" "}
            </h1>
            <h1 className="my-1 text-sm sm:text-lg lg:text-6xl">
              {" "}
              Whoever refreshes
            </h1>
            <h1 className="my-1 text-sm sm:text-lg lg:text-6xl">
              {" "}
              Others will be
            </h1>
            <h1 className="mb-5 text-sm sm:text-lg lg:text-6xl"> refreshed.</h1>

            <h1 className="sm:text-1xl mb-5 text-sm lg:text-lg">
              Proverbs 11:25{" "}
            </h1>
          </div>
          <Image
            src="/About-us-top-bg.png"
            alt="top-bg"
            width={100}
            height={500}
            layout="responsive"
            className=""
          />
        </div>

        <div className="relative w-screen font-bold text-white">
          <div className="absolute left-20 top-10 ml-5 w-full sm:top-40 md:left-10 lg:left-40 lg:top-80 lg:text-7xl">
            <div className="grid grid-cols-6" style={{ height: "30rem" }}>
              <h1 className="col-span-2">
                Ways <br></br> We <br />
                Give
                <br />
              </h1>

              <GivingAccordion colSpan={4} />
            </div>

            <div className="col-start absolute top-40  col-span-1 mt-10">
              <Button
                color="success"
                size="lg"
                className="text-bold bg-[#00EDC2] px-5 py-2 text-lg text-black

                "
              >
                Give Now
                <ArrowLongRightIcon className="size-5 w-12" />
              </Button>
            </div>
          </div>

          {/* <div className="right-50 absolute top-20"></div> */}
          <Image
            src="/About-us-middle-bg.png"
            width={100}
            height={600}
            layout="responsive"
            alt={""}
          />
        </div>

        <div className="min-w-screen relative mt-5 w-screen  flex-row items-center justify-center overflow-hidden text-center">
          <h1 className="lg:text-1xl my-5 justify-center text-sm font-bold sm:text-4xl">
            {" "}
            Why Should I tithe?{" "}
          </h1>
          <h1 className="lg:text-1xl my-5 text-sm font-bold sm:text-4xl">
            When you tithe, you’re trusting God with your finances.
          </h1>
          <p className="lg:text-1xl mb-10 text-sm leading-10 sm:text-2xl">
            Tithing is a biblical principle. God calls us to give the first 10%
            of our income back to
            <br />
            Him. We’ve seen God provide abundantly in our church, and we know He
            will provide
            <br />
            abundantly for you and your family when you put Him first in your
            finances. In fact, it’s
            <br />
            the one area in the Bible where God tells you to test Him.
            <br />
            <br />
            <br />
            Malachi 3:10, God tells us to bring tithe, which is 10% of our
            income, to Him. Later,
            <br />
            Jesus affirms this in the New Testament.
          </p>
        </div>

        {/* #D9D9D9 */}
        <div className="min-w-screen relative mt-10 w-screen items-center justify-center overflow-hidden bg-[#D9D9D9] text-center">
          <br />
          <br />
          <h1 className="my-10 mt-10 text-8xl font-bold ">Need Help?</h1>
          <h1 className="my-5 text-xl">
            If you’ve got questions about what you can give and how to give it,
            we’d love to help you figure it out.{" "}
          </h1>
          <Button className="my-5 rounded-none border-b-4	border-b-black bg-[#D9D9D9] p-10 ">
            <h1 className="  inline-block text-7xl font-bold">
              {" "}
              Let&apos;s Talk{" "}
              <ArrowLongRightIcon className="size-20 inline-block w-10" />{" "}
            </h1>
          </Button>
        </div>
      </main>
    </>
  );
}
