import Head from "next/head";
import AboutUs from "src/pages/AboutUs";
// import Giving from "src/pages/Giving";

export default function Home() {
  return (
    <>
      <Head>
        <title>About Us</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <AboutUs />
        {/* <Giving /> */}
      </main>
    </>
  );
}
