import Head from "next/head";
import Link from "next/link";
import Image from "next/image";

export default function ExperienceImages() {
  const hallowTxtStyle =
    "-1px -1px 0 #f8fafc, 1px -1px 0 #f8fafc, -1px 1px 0 #f8fafc, 1px 1px 0 #f8fafc";
  const coreValueTxtStyle =
    "text-sm sm:text-2xl lg:text-4xl -translate-y-4 sm:-translate-y-4 ";
  const coreValueNumStyle =
    "text-[#241F20] text-2xl sm:text-4xl lg:text-8xl -translate-y-3 sm:-translate-y-4 lg:-translate-y-7 border-t-8 border-white-500";

  return (
    <>
      <Head>
        <title> </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="gird-cols-1 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
          <Image
            src="/encountering-jesus.png"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/experiencing-family.png"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/promoting-discipleship.png"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/growing-spiritually.png"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />
        </div>
      </main>
    </>
  );
}
