import Head from "next/head";
import Image from "next/image";

export default function ExperienceImages() {
  return (
    <>
      <Head>
        <title> </title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="gird-cols-1 grid gap-2 sm:grid-cols-2 lg:grid-cols-4">
          <Image
            src="/images/experience-gallery/encountering-jesus.png"
            alt="encounter-jesus"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/images/experience-gallery/experiencing-family.png"
            alt="experiencing-family"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/images/experience-gallery/promoting-discipleship.png"
            alt="promoting-discipleship"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />

          <Image
            src="/images/experience-gallery/growing-spiritually.png"
            alt="growing-spiritually"
            width={800}
            height={600}
            layout=""
            className="mb-5"
          />
        </div>
      </main>
    </>
  );
}
